INFO 2025-10-12 15:45:01,779 autoreload 15160 15164 Watching for file changes with StatReloader
INFO 2025-10-12 15:45:45,217 basehttp 15160 14712 "GET /admin/auth/user/ HTTP/1.1" 200 16870
INFO 2025-10-12 15:45:54,959 basehttp 15160 14712 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 15:46:56,988 basehttp 15160 14580 "GET /admin/Sales/product/ HTTP/1.1" 200 14734
INFO 2025-10-12 15:47:02,047 basehttp 15160 14580 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 15:47:17,575 basehttp 15160 6776 "GET /admin/Sales/category/ HTTP/1.1" 200 12956
INFO 2025-10-12 15:47:20,493 basehttp 15160 14580 - Broken pipe from ('127.0.0.1', 53146)
INFO 2025-10-12 15:47:24,840 basehttp 15160 6776 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 15:47:41,155 basehttp 15160 6776 "GET /admin/Sales/category/add/ HTTP/1.1" 200 18439
INFO 2025-10-12 15:47:41,418 basehttp 15160 6776 "GET /static/admin/css/forms.css HTTP/1.1" 200 8525
INFO 2025-10-12 15:47:41,429 basehttp 15160 6380 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2025-10-12 15:47:41,454 basehttp 15160 6776 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11973
INFO 2025-10-12 15:47:41,461 basehttp 15160 7596 "GET /static/admin/js/inlines.js HTTP/1.1" 200 15628
INFO 2025-10-12 15:47:41,519 basehttp 15160 7596 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2025-10-12 15:47:46,238 basehttp 15160 14568 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 15:47:46,334 basehttp 15160 14568 "GET /static/admin/img/inline-delete.svg HTTP/1.1" 200 537
INFO 2025-10-12 15:49:09,246 basehttp 15160 14568 "POST /admin/Sales/category/add/ HTTP/1.1" 302 0
INFO 2025-10-12 15:49:13,278 basehttp 15160 14568 "GET /admin/Sales/category/ HTTP/1.1" 200 14634
INFO 2025-10-12 15:49:16,568 basehttp 15160 14568 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 15:50:53,242 basehttp 15160 14568 "GET /admin/Sales/subcategory/ HTTP/1.1" 200 16183
INFO 2025-10-12 15:50:56,425 basehttp 15160 14568 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 15:51:17,207 basehttp 15160 14568 "GET /admin/Sales/subcategory/1/change/ HTTP/1.1" 200 16961
INFO 2025-10-12 15:51:20,988 basehttp 15160 14568 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 15:51:49,128 basehttp 15160 7596 "GET /admin/Sales/product/ HTTP/1.1" 200 14734
INFO 2025-10-12 15:51:49,128 basehttp 15160 14568 - Broken pipe from ('127.0.0.1', 53161)
INFO 2025-10-12 15:51:53,772 basehttp 15160 7596 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 15:52:20,214 basehttp 15160 7596 "GET /admin/Sales/product/add/ HTTP/1.1" 200 21150
INFO 2025-10-12 15:52:25,803 basehttp 15160 7596 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 15:55:06,300 basehttp 15160 7596 "POST /admin/Sales/product/add/ HTTP/1.1" 302 0
INFO 2025-10-12 15:55:15,458 basehttp 15160 7596 "GET /admin/Sales/product/ HTTP/1.1" 200 17801
INFO 2025-10-12 15:55:19,947 basehttp 15160 7596 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 15:55:44,332 basehttp 15160 7596 "GET /admin/Sales/product/ HTTP/1.1" 200 17558
INFO 2025-10-12 15:55:48,886 basehttp 15160 7596 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 17:43:17,048 basehttp 15160 2408 "OPTIONS /api/token/ HTTP/1.1" 200 0
ERROR 2025-10-12 17:43:25,264 log 15160 2408 Internal Server Error: /api/token/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\views.py", line 46, in post
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 73, in validate
    data = super().validate(attrs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 57, in validate
    raise exceptions.AuthenticationFailed(
    ...<2 lines>...
    )
rest_framework.exceptions.AuthenticationFailed: No active account found with the given credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'inventory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'inventory.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'inventory'.
ERROR 2025-10-12 17:43:25,295 basehttp 15160 2408 "POST /api/token/ HTTP/1.1" 500 159217
INFO 2025-10-12 17:49:05,745 autoreload 15160 15164 C:\Users\user\OneDrive\Desktop\Inventory\Stock\Stock\settings.py changed, reloading.
INFO 2025-10-12 17:49:08,169 autoreload 11892 14004 Watching for file changes with StatReloader
ERROR 2025-10-12 17:50:02,004 log 11892 9836 Internal Server Error: /api/token/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\views.py", line 46, in post
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 73, in validate
    data = super().validate(attrs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 57, in validate
    raise exceptions.AuthenticationFailed(
    ...<2 lines>...
    )
rest_framework.exceptions.AuthenticationFailed: No active account found with the given credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sales'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'sales.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'sales'.
ERROR 2025-10-12 17:50:02,030 basehttp 11892 9836 "POST /api/token/ HTTP/1.1" 500 159065
INFO 2025-10-12 17:51:55,126 autoreload 11892 14004 C:\Users\user\OneDrive\Desktop\Inventory\Stock\Stock\settings.py changed, reloading.
INFO 2025-10-12 17:51:56,661 autoreload 12056 15332 Watching for file changes with StatReloader
INFO 2025-10-12 17:52:56,428 basehttp 12056 10300 "GET /admin/auth/user/ HTTP/1.1" 200 16870
INFO 2025-10-12 17:53:00,816 basehttp 12056 10300 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 17:53:10,238 basehttp 12056 10300 "GET /admin/auth/user/add/ HTTP/1.1" 200 17546
INFO 2025-10-12 17:53:10,421 basehttp 12056 10300 "GET /static/admin/css/unusable_password_field.css HTTP/1.1" 200 663
INFO 2025-10-12 17:53:10,467 basehttp 12056 10300 "GET /static/admin/js/unusable_password_field.js HTTP/1.1" 200 1480
INFO 2025-10-12 17:53:15,242 basehttp 12056 15296 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 17:54:12,334 basehttp 12056 15296 "POST /admin/auth/user/add/ HTTP/1.1" 200 17850
INFO 2025-10-12 17:54:16,352 basehttp 12056 15296 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 17:56:03,869 basehttp 12056 15296 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2025-10-12 17:56:21,340 basehttp 12056 15296 "GET /admin/auth/user/2/change/ HTTP/1.1" 200 30625
INFO 2025-10-12 17:56:21,922 basehttp 12056 8944 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO 2025-10-12 17:56:21,923 basehttp 12056 10300 "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
INFO 2025-10-12 17:56:21,930 basehttp 12056 9016 "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
INFO 2025-10-12 17:56:21,931 basehttp 12056 13128 "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15845
INFO 2025-10-12 17:56:25,959 basehttp 12056 15296 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 17:56:26,148 basehttp 12056 9016 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2025-10-12 17:56:26,150 basehttp 12056 13128 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2025-10-12 17:56:26,151 basehttp 12056 15296 "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2025-10-12 18:04:14,475 basehttp 12056 14676 "POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
INFO 2025-10-12 18:04:25,318 basehttp 12056 14676 "GET /admin/auth/user/ HTTP/1.1" 200 17559
INFO 2025-10-12 18:04:55,484 basehttp 12056 14676 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 18:05:50,606 basehttp 12056 9288 "POST /api/token/ HTTP/1.1" 200 489
INFO 2025-10-12 18:05:50,611 basehttp 12056 9288 "OPTIONS /api/users/me/ HTTP/1.1" 200 0
INFO 2025-10-12 18:05:56,374 basehttp 12056 9288 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-12 18:05:56,492 basehttp 12056 9288 "OPTIONS /api/dashboard/summary/ HTTP/1.1" 200 0
INFO 2025-10-12 18:05:56,492 basehttp 12056 15356 "OPTIONS /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 0
INFO 2025-10-12 18:05:56,496 basehttp 12056 15356 "OPTIONS /api/dashboard/summary/ HTTP/1.1" 200 0
INFO 2025-10-12 18:05:56,496 basehttp 12056 9288 "OPTIONS /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 0
INFO 2025-10-12 18:06:01,957 basehttp 12056 15356 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-12 18:06:05,039 basehttp 12056 9288 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-12 18:06:06,658 basehttp 12056 15356 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-12 18:06:11,244 basehttp 12056 9288 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-12 18:06:31,351 basehttp 12056 9288 "OPTIONS /api/products/ HTTP/1.1" 200 0
INFO 2025-10-12 18:06:31,354 basehttp 12056 15356 "OPTIONS /api/categories/ HTTP/1.1" 200 0
INFO 2025-10-12 18:06:31,369 basehttp 12056 15356 "OPTIONS /api/subcategories/ HTTP/1.1" 200 0
INFO 2025-10-12 18:06:31,369 basehttp 12056 9288 "OPTIONS /api/subcategories/ HTTP/1.1" 200 0
INFO 2025-10-12 18:06:34,809 basehttp 12056 15356 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-12 18:06:35,568 basehttp 12056 10564 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-12 18:06:36,891 basehttp 12056 4340 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-12 18:06:40,417 basehttp 12056 10564 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-12 18:06:41,231 basehttp 12056 15356 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-12 18:06:42,530 basehttp 12056 4340 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-12 18:06:53,013 basehttp 12056 4340 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-12 18:06:57,150 basehttp 12056 10564 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-12 18:06:58,165 basehttp 12056 4340 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-12 18:07:01,051 basehttp 12056 15356 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-12 18:07:01,844 basehttp 12056 10564 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-12 18:07:08,841 basehttp 12056 15356 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-12 18:07:17,721 basehttp 12056 15356 "OPTIONS /api/invoices/ HTTP/1.1" 200 0
INFO 2025-10-12 18:07:17,724 basehttp 12056 10564 "OPTIONS /api/customers/ HTTP/1.1" 200 0
INFO 2025-10-12 18:07:17,724 basehttp 12056 9288 "OPTIONS /api/customers/ HTTP/1.1" 200 0
INFO 2025-10-12 18:07:17,724 basehttp 12056 4340 "OPTIONS /api/invoices/ HTTP/1.1" 200 0
INFO 2025-10-12 18:07:21,707 basehttp 12056 9288 "GET /api/invoices/ HTTP/1.1" 200 52
INFO 2025-10-12 18:07:22,213 basehttp 12056 10564 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-12 18:07:22,900 basehttp 12056 4340 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-12 18:07:25,215 basehttp 12056 9288 "GET /api/invoices/ HTTP/1.1" 200 52
INFO 2025-10-12 18:07:26,091 basehttp 12056 10564 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-12 18:07:35,133 basehttp 12056 4340 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-12 18:31:30,785 autoreload 9296 14600 Watching for file changes with StatReloader
INFO 2025-10-12 18:31:59,457 basehttp 9296 10264 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-12 18:32:03,483 basehttp 9296 10264 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-12 18:32:04,336 basehttp 9296 12556 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-12 18:32:06,458 basehttp 9296 10272 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-12 18:32:07,931 basehttp 9296 12556 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-12 18:32:09,159 basehttp 9296 13548 "GET /admin/auth/user/ HTTP/1.1" 200 17359
INFO 2025-10-12 18:32:14,899 basehttp 9296 13548 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-12 18:32:15,099 basehttp 9296 10272 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-12 18:32:24,358 basehttp 9296 12760 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-12 18:32:29,797 basehttp 9296 12760 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-12 18:32:30,337 basehttp 9296 10272 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-12 18:32:34,883 basehttp 9296 12760 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-12 18:32:36,087 basehttp 9296 10272 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-12 18:32:37,177 basehttp 9296 14412 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-12 18:32:37,400 basehttp 9296 13648 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-12 18:32:37,789 basehttp 9296 10712 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-12 18:32:39,208 basehttp 9296 12760 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-12 18:32:42,478 basehttp 9296 10272 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-12 18:32:42,883 basehttp 9296 10712 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-12 18:32:43,223 basehttp 9296 13648 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-12 18:32:45,053 basehttp 9296 14412 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-12 18:32:50,782 basehttp 9296 10272 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-12 18:32:57,350 basehttp 9296 796 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-12 18:32:58,180 basehttp 9296 11452 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-12 18:32:58,295 basehttp 9296 10272 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-12 18:33:02,595 basehttp 9296 796 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-12 18:33:02,919 basehttp 9296 11452 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-12 18:33:02,952 basehttp 9296 10272 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-12 18:40:28,094 basehttp 9296 15088 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-12 18:40:32,290 basehttp 9296 6188 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-12 18:40:33,138 basehttp 9296 14164 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-12 18:40:33,575 basehttp 9296 14768 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-12 18:40:34,099 basehttp 9296 15088 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-12 18:40:37,002 basehttp 9296 14164 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-12 18:40:37,267 basehttp 9296 6188 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-12 18:40:37,267 basehttp 9296 14768 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-12 18:41:30,242 basehttp 9296 11452 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-12 18:41:34,411 basehttp 9296 11452 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-12 18:41:35,599 basehttp 9296 3560 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-12 18:41:36,569 basehttp 9296 13540 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-12 18:41:38,853 basehttp 9296 10288 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-12 18:41:39,054 basehttp 9296 14464 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-12 18:41:39,790 basehttp 9296 3560 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-12 18:41:40,412 basehttp 9296 13540 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-12 18:41:40,612 basehttp 9296 14576 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-12 18:41:44,660 basehttp 9296 10288 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-12 18:41:45,168 basehttp 9296 14464 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-12 18:41:49,499 basehttp 9296 14576 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-13 09:50:58,662 autoreload 12132 6460 Watching for file changes with StatReloader
INFO 2025-10-13 09:53:10,695 basehttp 12132 10724 "GET /admin/ HTTP/1.1" 200 15206
INFO 2025-10-13 09:53:10,895 basehttp 12132 8572 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-10-13 09:53:10,897 basehttp 12132 10724 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-10-13 09:53:10,898 basehttp 12132 10048 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-10-13 09:53:10,909 basehttp 12132 13608 "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2025-10-13 09:53:10,911 basehttp 12132 5052 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-10-13 09:53:10,918 basehttp 12132 1112 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-10-13 09:53:10,953 basehttp 12132 13608 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2025-10-13 09:53:10,953 basehttp 12132 5052 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-10-13 09:53:10,956 basehttp 12132 1112 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
WARNING 2025-10-13 09:53:11,266 log 12132 1112 Not Found: /favicon.ico
WARNING 2025-10-13 09:53:11,267 basehttp 12132 1112 "GET /favicon.ico HTTP/1.1" 404 3037
INFO 2025-10-13 09:53:21,308 basehttp 12132 10960 "OPTIONS /api/users/me/ HTTP/1.1" 200 0
INFO 2025-10-13 09:53:21,514 basehttp 12132 10960 "OPTIONS /api/users/me/ HTTP/1.1" 200 0
ERROR 2025-10-13 09:53:22,164 log 12132 9964 Internal Server Error: /api/users/me/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
    ...<4 lines>...
    )
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='Given token not valid for any token type', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='Token is expired', code='token_not_valid')}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-13 09:53:22,203 basehttp 12132 9964 "GET /api/users/me/ HTTP/1.1" 500 163668
ERROR 2025-10-13 09:53:22,308 log 12132 10960 Internal Server Error: /api/users/me/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
    ...<4 lines>...
    )
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='Given token not valid for any token type', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='Token is expired', code='token_not_valid')}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-13 09:53:22,400 basehttp 12132 10960 "GET /api/users/me/ HTTP/1.1" 500 163668
INFO 2025-10-13 09:53:46,746 basehttp 12132 10960 "OPTIONS /api/token/ HTTP/1.1" 200 0
INFO 2025-10-13 09:53:50,946 basehttp 12132 10960 "POST /api/token/ HTTP/1.1" 200 489
INFO 2025-10-13 09:53:54,150 basehttp 12132 10960 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-13 09:53:54,604 basehttp 12132 9964 "OPTIONS /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 0
INFO 2025-10-13 09:53:54,604 basehttp 12132 10960 "OPTIONS /api/dashboard/summary/ HTTP/1.1" 200 0
INFO 2025-10-13 09:53:54,604 basehttp 12132 13224 "OPTIONS /api/dashboard/summary/ HTTP/1.1" 200 0
INFO 2025-10-13 09:53:54,615 basehttp 12132 9964 "OPTIONS /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 0
INFO 2025-10-13 09:53:57,810 basehttp 12132 10960 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-13 09:53:59,395 basehttp 12132 13224 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-13 09:54:01,212 basehttp 12132 2948 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-13 09:54:04,472 basehttp 12132 7464 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-13 10:11:13,564 basehttp 12132 14836 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-13 10:11:15,127 basehttp 12132 13104 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-13 10:11:16,800 basehttp 12132 14836 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-13 10:11:19,736 basehttp 12132 13104 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-13 11:21:36,492 basehttp 12132 11384 "GET /admin/Sales/supplier/ HTTP/1.1" 200 14741
INFO 2025-10-13 11:21:36,493 basehttp 12132 11700 - Broken pipe from ('127.0.0.1', 56908)
INFO 2025-10-13 11:21:36,549 basehttp 12132 11384 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2025-10-13 11:21:36,557 basehttp 12132 4088 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-10-13 11:21:36,557 basehttp 12132 11384 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-10-13 11:21:36,561 basehttp 12132 14424 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-10-13 11:21:36,564 basehttp 12132 13980 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-10-13 11:21:36,566 basehttp 12132 14760 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-10-13 11:21:36,570 basehttp 12132 11384 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-10-13 11:21:36,573 basehttp 12132 4088 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-10-13 11:21:36,583 basehttp 12132 13980 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-10-13 11:21:36,589 basehttp 12132 11384 "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2025-10-13 11:21:36,606 basehttp 12132 11384 "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2025-10-13 11:21:39,679 basehttp 12132 10780 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-13 11:21:39,826 basehttp 12132 10780 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2025-10-13 11:21:39,828 basehttp 12132 11384 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO 2025-10-13 11:21:48,543 basehttp 12132 11384 "GET /admin/Sales/supplier/add/ HTTP/1.1" 200 18103
INFO 2025-10-13 11:21:48,579 basehttp 12132 11384 "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2025-10-13 11:21:48,581 basehttp 12132 13980 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2025-10-13 11:21:48,590 basehttp 12132 13980 "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2025-10-13 11:21:48,592 basehttp 12132 11384 "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2025-10-13 11:21:51,709 basehttp 12132 10780 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-13 11:26:36,976 basehttp 12132 10680 "POST /admin/Sales/supplier/add/ HTTP/1.1" 302 0
INFO 2025-10-13 11:26:42,255 basehttp 12132 10680 "GET /admin/Sales/supplier/ HTTP/1.1" 200 17096
INFO 2025-10-13 11:26:42,302 basehttp 12132 2700 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2025-10-13 11:26:46,338 basehttp 12132 10680 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-13 11:26:55,926 basehttp 12132 10680 "GET /admin/Sales/supplier/add/ HTTP/1.1" 200 18103
INFO 2025-10-13 11:26:59,879 basehttp 12132 10680 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-13 11:28:01,282 basehttp 12132 10680 - Broken pipe from ('127.0.0.1', 56955)
INFO 2025-10-13 11:28:03,491 basehttp 12132 2700 "POST /admin/Sales/supplier/add/ HTTP/1.1" 200 18451
INFO 2025-10-13 11:28:06,824 basehttp 12132 2700 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-13 11:28:53,483 basehttp 12132 2700 "POST /admin/Sales/supplier/add/ HTTP/1.1" 302 0
INFO 2025-10-13 11:28:57,533 basehttp 12132 2700 "GET /admin/Sales/supplier/ HTTP/1.1" 200 18154
INFO 2025-10-13 11:29:00,686 basehttp 12132 2700 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-10-13 11:29:14,638 log 12132 14096 Internal Server Error: /api/users/me/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
    ...<4 lines>...
    )
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='Given token not valid for any token type', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='Token is expired', code='token_not_valid')}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-13 11:29:14,674 basehttp 12132 14096 "GET /api/users/me/ HTTP/1.1" 500 163668
ERROR 2025-10-13 11:29:14,767 log 12132 240 Internal Server Error: /api/users/me/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
    ...<4 lines>...
    )
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='Given token not valid for any token type', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='Token is expired', code='token_not_valid')}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-13 11:29:14,792 basehttp 12132 240 "GET /api/users/me/ HTTP/1.1" 500 163668
INFO 2025-10-13 11:29:20,147 basehttp 12132 2700 "GET /admin/Sales/supplier/ HTTP/1.1" 200 17946
INFO 2025-10-13 11:29:23,283 basehttp 12132 2700 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-13 11:32:49,209 basehttp 12132 240 "POST /api/token/ HTTP/1.1" 200 489
INFO 2025-10-13 11:32:52,284 basehttp 12132 240 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-13 11:32:55,488 basehttp 12132 14096 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-13 11:32:57,136 basehttp 12132 240 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-13 11:32:58,637 basehttp 12132 14096 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-13 11:33:01,807 basehttp 12132 240 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-13 11:45:29,112 basehttp 12132 14840 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-13 11:45:32,247 basehttp 12132 14840 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-13 11:45:32,586 basehttp 12132 856 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-13 11:45:33,795 basehttp 12132 2404 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-13 11:45:35,671 basehttp 12132 856 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-13 11:45:38,540 basehttp 12132 2404 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-13 11:45:42,444 basehttp 12132 856 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-13 11:45:44,032 basehttp 12132 2404 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-13 11:45:45,529 basehttp 12132 856 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-13 11:45:48,691 basehttp 12132 2404 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-15 09:52:03,814 autoreload 1752 12752 Watching for file changes with StatReloader
INFO 2025-10-15 09:52:38,523 basehttp 1752 1532 "GET /admin/ HTTP/1.1" 200 16284
INFO 2025-10-15 09:52:39,028 basehttp 1752 9800 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-10-15 09:52:39,032 basehttp 1752 1532 "GET /static/admin/css/base.css HTTP/1.1" 200 22120
INFO 2025-10-15 09:52:39,039 basehttp 1752 7688 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
INFO 2025-10-15 09:52:39,045 basehttp 1752 8488 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-10-15 09:52:39,050 basehttp 1752 15332 "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
INFO 2025-10-15 09:52:39,130 basehttp 1752 5700 "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-10-15 09:52:39,142 basehttp 1752 8488 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-10-15 09:52:39,189 basehttp 1752 5700 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-10-15 09:52:39,191 basehttp 1752 8488 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
WARNING 2025-10-15 09:52:39,412 log 1752 8488 Not Found: /favicon.ico
WARNING 2025-10-15 09:52:39,413 basehttp 1752 8488 "GET /favicon.ico HTTP/1.1" 404 3037
INFO 2025-10-15 10:57:36,862 basehttp 1752 3096 "OPTIONS /api/users/me/ HTTP/1.1" 200 0
INFO 2025-10-15 10:57:36,863 basehttp 1752 8768 "OPTIONS /api/users/me/ HTTP/1.1" 200 0
ERROR 2025-10-15 10:57:37,294 log 1752 3096 Internal Server Error: /api/users/me/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
    ...<4 lines>...
    )
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='Given token not valid for any token type', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='Token is expired', code='token_not_valid')}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-15 10:57:37,319 basehttp 1752 3096 "GET /api/users/me/ HTTP/1.1" 500 163527
ERROR 2025-10-15 10:57:37,440 log 1752 8768 Internal Server Error: /api/users/me/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
    ...<4 lines>...
    )
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='Given token not valid for any token type', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='Token is expired', code='token_not_valid')}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-15 10:57:37,475 basehttp 1752 8768 "GET /api/users/me/ HTTP/1.1" 500 163527
INFO 2025-10-15 10:57:42,905 basehttp 1752 12940 "GET /admin/ HTTP/1.1" 200 16284
INFO 2025-10-15 10:58:40,578 basehttp 1752 8768 "OPTIONS /api/token/ HTTP/1.1" 200 0
INFO 2025-10-15 10:58:44,644 basehttp 1752 8768 "POST /api/token/ HTTP/1.1" 200 489
INFO 2025-10-15 10:58:47,911 basehttp 1752 8768 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-15 10:58:48,058 basehttp 1752 8768 "OPTIONS /api/dashboard/summary/ HTTP/1.1" 200 0
INFO 2025-10-15 10:58:48,060 basehttp 1752 3096 "OPTIONS /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 0
INFO 2025-10-15 10:58:48,062 basehttp 1752 8768 "OPTIONS /api/dashboard/summary/ HTTP/1.1" 200 0
INFO 2025-10-15 10:58:48,067 basehttp 1752 3096 "OPTIONS /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 0
INFO 2025-10-15 10:58:51,318 basehttp 1752 3096 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 10:58:52,638 basehttp 1752 8768 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-15 10:58:54,565 basehttp 1752 3096 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 10:58:57,323 basehttp 1752 8768 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-15 10:59:52,882 basehttp 1752 8768 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-15 10:59:56,016 basehttp 1752 8768 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-15 10:59:56,374 basehttp 1752 12444 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 10:59:57,528 basehttp 1752 3096 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-15 10:59:59,516 basehttp 1752 12444 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 11:00:02,152 basehttp 1752 3096 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-15 11:00:43,526 basehttp 1752 3096 "OPTIONS /api/lpos/ HTTP/1.1" 200 0
INFO 2025-10-15 11:00:43,527 basehttp 1752 12444 "OPTIONS /api/suppliers/ HTTP/1.1" 200 0
INFO 2025-10-15 11:00:43,530 basehttp 1752 8768 "OPTIONS /api/products/ HTTP/1.1" 200 0
INFO 2025-10-15 11:00:46,711 basehttp 1752 3096 "GET /api/lpos/ HTTP/1.1" 200 52
INFO 2025-10-15 11:00:47,028 basehttp 1752 8768 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 11:00:47,029 basehttp 1752 12444 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 11:00:50,520 basehttp 1752 3096 "GET /api/lpos/ HTTP/1.1" 200 52
INFO 2025-10-15 11:00:50,574 basehttp 1752 12444 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 11:00:50,587 basehttp 1752 8768 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 11:03:47,231 basehttp 1752 8768 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-15 11:03:50,305 basehttp 1752 8768 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-15 11:03:50,372 basehttp 1752 12444 "GET /api/lpos/ HTTP/1.1" 200 52
INFO 2025-10-15 11:03:50,731 basehttp 1752 3096 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 11:03:51,026 basehttp 1752 15616 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 11:03:53,527 basehttp 1752 12444 "GET /api/lpos/ HTTP/1.1" 200 52
INFO 2025-10-15 11:03:54,172 basehttp 1752 3096 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 11:03:54,566 basehttp 1752 15616 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 11:06:47,535 basehttp 1752 15616 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-15 11:06:50,628 basehttp 1752 15616 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-15 11:06:50,663 basehttp 1752 12444 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 11:06:52,346 basehttp 1752 3096 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-15 11:06:53,795 basehttp 1752 12444 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 11:06:57,018 basehttp 1752 3096 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-15 11:06:58,899 basehttp 1752 3096 "OPTIONS /api/categories/ HTTP/1.1" 200 0
INFO 2025-10-15 11:06:58,901 basehttp 1752 12444 "OPTIONS /api/subcategories/ HTTP/1.1" 200 0
INFO 2025-10-15 11:06:58,903 basehttp 1752 15616 "OPTIONS /api/categories/ HTTP/1.1" 200 0
INFO 2025-10-15 11:06:58,904 basehttp 1752 8768 "OPTIONS /api/subcategories/ HTTP/1.1" 200 0
INFO 2025-10-15 11:07:02,351 basehttp 1752 12444 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 11:07:02,422 basehttp 1752 15616 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-15 11:07:02,734 basehttp 1752 8768 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-15 11:07:05,728 basehttp 1752 12444 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 11:07:05,841 basehttp 1752 15616 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-15 11:07:06,479 basehttp 1752 8768 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-15 11:27:04,622 basehttp 1752 916 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-15 11:27:07,683 basehttp 1752 916 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-15 11:27:08,026 basehttp 1752 8956 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 11:27:09,260 basehttp 1752 8168 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-15 11:27:11,108 basehttp 1752 8956 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 11:27:13,822 basehttp 1752 8168 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
ERROR 2025-10-15 12:06:00,624 log 1752 5292 Internal Server Error: /api/users/me/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
    ...<4 lines>...
    )
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='Given token not valid for any token type', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='Token is expired', code='token_not_valid')}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-15 12:06:00,732 basehttp 1752 5292 "GET /api/users/me/ HTTP/1.1" 500 163527
ERROR 2025-10-15 12:06:00,844 log 1752 15268 Internal Server Error: /api/users/me/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
    ...<4 lines>...
    )
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='Given token not valid for any token type', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='Token is expired', code='token_not_valid')}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-15 12:06:00,882 basehttp 1752 15268 "GET /api/users/me/ HTTP/1.1" 500 163527
INFO 2025-10-15 12:10:40,805 basehttp 1752 15112 "GET /admin/ HTTP/1.1" 200 16284
INFO 2025-10-15 12:11:27,660 basehttp 1752 8916 "POST /api/token/ HTTP/1.1" 200 489
INFO 2025-10-15 12:11:30,760 basehttp 1752 8916 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-15 12:11:34,044 basehttp 1752 13504 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 12:11:35,558 basehttp 1752 8916 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-15 12:11:37,290 basehttp 1752 13504 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 12:11:40,299 basehttp 1752 8916 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-15 12:11:43,700 basehttp 1752 13504 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 12:11:44,022 basehttp 1752 13204 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-15 12:11:44,022 basehttp 1752 8916 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-15 12:11:47,239 basehttp 1752 13504 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 12:11:47,419 basehttp 1752 13204 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-15 12:11:47,715 basehttp 1752 8916 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-15 12:12:10,992 basehttp 1752 8916 "OPTIONS /api/invoices/ HTTP/1.1" 200 0
INFO 2025-10-15 12:12:10,994 basehttp 1752 13204 "OPTIONS /api/customers/ HTTP/1.1" 200 0
INFO 2025-10-15 12:12:14,138 basehttp 1752 8916 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:12:14,161 basehttp 1752 13204 "GET /api/invoices/ HTTP/1.1" 200 52
INFO 2025-10-15 12:12:14,476 basehttp 1752 13504 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 12:12:17,211 basehttp 1752 8916 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:12:17,365 basehttp 1752 13204 "GET /api/invoices/ HTTP/1.1" 200 52
INFO 2025-10-15 12:12:17,886 basehttp 1752 13504 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 12:12:18,435 basehttp 1752 13504 "OPTIONS /api/invoices/outstanding/ HTTP/1.1" 200 0
INFO 2025-10-15 12:12:21,566 basehttp 1752 13204 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:12:21,589 basehttp 1752 13504 "GET /api/invoices/outstanding/ HTTP/1.1" 200 2
INFO 2025-10-15 12:12:21,898 basehttp 1752 8916 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 12:12:34,558 basehttp 1752 8916 "GET /api/invoices/outstanding/ HTTP/1.1" 200 2
INFO 2025-10-15 12:12:34,564 basehttp 1752 13504 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:12:34,880 basehttp 1752 13204 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 12:12:37,302 basehttp 1752 7464 "GET /api/lpos/ HTTP/1.1" 200 52
INFO 2025-10-15 12:12:37,867 basehttp 1752 7888 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:12:38,307 basehttp 1752 13204 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 12:12:40,408 basehttp 1752 7464 "GET /api/lpos/ HTTP/1.1" 200 52
INFO 2025-10-15 12:12:41,210 basehttp 1752 7888 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:12:41,680 basehttp 1752 13204 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 12:12:45,744 basehttp 1752 13204 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:12:49,120 basehttp 1752 13204 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:12:58,471 basehttp 1752 13204 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:13:01,331 basehttp 1752 7464 "OPTIONS /api/stock-entries/ HTTP/1.1" 200 0
INFO 2025-10-15 12:13:01,331 basehttp 1752 7888 "OPTIONS /api/stock-entries/ HTTP/1.1" 200 0
INFO 2025-10-15 12:13:01,576 basehttp 1752 13204 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:13:04,448 basehttp 1752 7888 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-15 12:13:07,540 basehttp 1752 7888 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-15 12:13:14,473 basehttp 1752 7888 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 12:13:17,566 basehttp 1752 7888 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 12:13:25,296 basehttp 1752 13204 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-15 12:13:25,512 basehttp 1752 7888 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-15 12:13:28,740 basehttp 1752 13204 "GET /api/subcategories/ HTTP/1.1" 200 190
INFO 2025-10-15 12:13:29,291 basehttp 1752 7888 "GET /api/categories/ HTTP/1.1" 200 296
INFO 2025-10-15 12:19:13,606 basehttp 1752 13036 "POST /api/subcategories/ HTTP/1.1" 201 139
INFO 2025-10-15 12:19:17,034 basehttp 1752 13036 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 12:19:17,351 basehttp 1752 14148 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 12:19:31,851 basehttp 1752 9604 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 12:19:31,852 basehttp 1752 8008 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 12:19:32,119 basehttp 1752 3264 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 12:19:35,235 basehttp 1752 8008 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 12:19:35,274 basehttp 1752 9604 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 12:19:35,798 basehttp 1752 3264 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 12:20:08,650 basehttp 1752 3264 "GET /api/products/ HTTP/1.1" 200 397
INFO 2025-10-15 12:20:08,664 basehttp 1752 8008 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 12:20:08,910 basehttp 1752 9604 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 12:21:22,284 basehttp 1752 9604 "POST /api/products/ HTTP/1.1" 201 339
INFO 2025-10-15 12:21:25,735 basehttp 1752 3264 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 12:21:25,736 basehttp 1752 9604 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:21:26,003 basehttp 1752 8008 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 12:21:38,739 basehttp 1752 8008 "GET /api/lpos/ HTTP/1.1" 200 52
INFO 2025-10-15 12:21:39,021 basehttp 1752 3264 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:21:39,068 basehttp 1752 9604 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:21:41,850 basehttp 1752 8008 "GET /api/lpos/ HTTP/1.1" 200 52
INFO 2025-10-15 12:21:42,408 basehttp 1752 3264 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:21:42,430 basehttp 1752 9604 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:24:51,117 basehttp 1752 9604 "GET /api/lpos/ HTTP/1.1" 200 52
INFO 2025-10-15 12:24:51,387 basehttp 1752 8008 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:24:51,392 basehttp 1752 3264 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:24:55,603 basehttp 1752 8008 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:24:55,612 basehttp 1752 3264 "GET /api/invoices/ HTTP/1.1" 200 52
INFO 2025-10-15 12:24:55,907 basehttp 1752 9604 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:24:58,663 basehttp 1752 8008 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:24:58,706 basehttp 1752 3264 "GET /api/invoices/ HTTP/1.1" 200 52
INFO 2025-10-15 12:24:59,349 basehttp 1752 9604 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:25:53,187 basehttp 1752 3264 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:25:53,188 basehttp 1752 9604 "GET /api/invoices/ HTTP/1.1" 200 52
INFO 2025-10-15 12:25:53,486 basehttp 1752 8008 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:25:56,577 basehttp 1752 9604 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-15 12:25:59,655 basehttp 1752 9604 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-15 12:30:15,327 basehttp 1752 8008 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:30:15,340 basehttp 1752 9604 "GET /api/invoices/ HTTP/1.1" 200 52
INFO 2025-10-15 12:30:15,669 basehttp 1752 3264 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:30:18,430 basehttp 1752 9604 "GET /api/invoices/ HTTP/1.1" 200 52
INFO 2025-10-15 12:30:18,447 basehttp 1752 8008 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:30:19,052 basehttp 1752 3264 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:40:49,390 basehttp 1752 15132 "GET /api/invoices/ HTTP/1.1" 200 52
INFO 2025-10-15 12:40:49,504 basehttp 1752 15476 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:40:49,724 basehttp 1752 7004 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:41:02,315 basehttp 1752 7004 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:41:05,636 basehttp 1752 15476 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:41:05,646 basehttp 1752 10712 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 12:41:05,730 basehttp 1752 7004 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:41:05,911 basehttp 1752 15132 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 12:41:09,038 basehttp 1752 15476 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:41:09,056 basehttp 1752 10712 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 12:41:09,599 basehttp 1752 15132 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 12:41:25,779 basehttp 1752 15132 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-15 12:41:28,907 basehttp 1752 15132 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-15 12:41:54,936 basehttp 1752 15132 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:41:57,693 basehttp 1752 10712 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:41:58,385 basehttp 1752 15132 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:42:00,770 basehttp 1752 10712 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-15 12:42:54,928 basehttp 1752 10712 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-15 12:42:58,075 basehttp 1752 10712 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-15 12:43:00,479 basehttp 1752 7004 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 12:43:00,512 basehttp 1752 15132 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:43:00,817 basehttp 1752 15476 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 12:43:03,877 basehttp 1752 7004 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 12:43:03,897 basehttp 1752 15132 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:43:04,558 basehttp 1752 15476 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 12:43:14,806 basehttp 1752 15476 "OPTIONS /api/products/low_stock/ HTTP/1.1" 200 0
INFO 2025-10-15 12:43:17,853 basehttp 1752 15476 "GET /api/products/low_stock/ HTTP/1.1" 200 347
INFO 2025-10-15 12:43:18,174 basehttp 1752 7004 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 12:43:18,524 basehttp 1752 15132 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 12:43:24,100 basehttp 1752 7004 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 12:43:25,648 basehttp 1752 15132 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-15 12:43:27,163 basehttp 1752 7004 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-15 12:43:30,210 basehttp 1752 15132 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-15 12:43:40,413 basehttp 1752 15476 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 12:43:40,457 basehttp 1752 15132 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:43:40,688 basehttp 1752 7004 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 12:43:43,842 basehttp 1752 15132 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:43:43,846 basehttp 1752 15476 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 12:43:44,413 basehttp 1752 7004 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 12:51:48,506 basehttp 1752 12304 "GET /api/lpos/ HTTP/1.1" 200 52
INFO 2025-10-15 12:51:48,856 basehttp 1752 11688 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:51:48,857 basehttp 1752 15660 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:51:51,654 basehttp 1752 12304 "GET /api/lpos/ HTTP/1.1" 200 52
INFO 2025-10-15 12:51:52,267 basehttp 1752 15660 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 12:51:52,285 basehttp 1752 11688 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:51:55,133 basehttp 1752 11688 "OPTIONS /api/lpos/pending/ HTTP/1.1" 200 0
INFO 2025-10-15 12:51:58,217 basehttp 1752 11688 "GET /api/lpos/pending/ HTTP/1.1" 200 2
INFO 2025-10-15 12:51:58,508 basehttp 1752 15660 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-15 12:51:58,557 basehttp 1752 12304 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 13:03:48,947 basehttp 1752 13072 "OPTIONS /api/products/ HTTP/1.1" 200 0
INFO 2025-10-15 13:03:48,948 basehttp 1752 14196 "OPTIONS /api/products/ HTTP/1.1" 200 0
INFO 2025-10-15 13:03:52,575 basehttp 1752 13072 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 13:03:52,582 basehttp 1752 10512 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 13:03:52,877 basehttp 1752 764 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 13:03:56,007 basehttp 1752 10512 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-15 13:03:56,030 basehttp 1752 13072 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-15 13:03:56,652 basehttp 1752 764 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-15 13:04:00,760 basehttp 1752 764 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-15 13:04:03,819 basehttp 1752 764 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-15 13:41:41,208 basehttp 1752 13100 "OPTIONS /api/users/me/ HTTP/1.1" 200 0
INFO 2025-10-15 13:41:41,213 basehttp 1752 9468 "OPTIONS /api/users/me/ HTTP/1.1" 200 0
ERROR 2025-10-15 13:41:41,359 log 1752 9468 Internal Server Error: /api/users/me/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
    ...<4 lines>...
    )
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='Given token not valid for any token type', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='Token is expired', code='token_not_valid')}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-15 13:41:41,608 basehttp 1752 9468 "GET /api/users/me/ HTTP/1.1" 500 163527
ERROR 2025-10-15 13:41:41,807 log 1752 13100 Internal Server Error: /api/users/me/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
    ...<4 lines>...
    )
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='Given token not valid for any token type', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='Token is expired', code='token_not_valid')}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-15 13:41:41,838 basehttp 1752 13100 "GET /api/users/me/ HTTP/1.1" 500 163527
INFO 2025-10-16 10:45:19,415 autoreload 12660 10932 Watching for file changes with StatReloader
INFO 2025-10-16 10:56:17,633 basehttp 12660 1116 "GET /admin/ HTTP/1.1" 200 16284
INFO 2025-10-16 10:56:17,931 basehttp 12660 1116 "GET /static/admin/css/base.css HTTP/1.1" 200 22120
INFO 2025-10-16 10:56:17,943 basehttp 12660 11524 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
INFO 2025-10-16 10:56:17,985 basehttp 12660 3696 "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-10-16 10:56:18,019 basehttp 12660 3696 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-10-16 10:56:18,028 basehttp 12660 11524 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-10-16 10:56:18,069 basehttp 12660 11524 "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
INFO 2025-10-16 10:56:18,191 basehttp 12660 11524 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-10-16 10:56:18,248 basehttp 12660 3696 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-10-16 10:56:18,250 basehttp 12660 11524 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
WARNING 2025-10-16 10:56:18,544 log 12660 11524 Not Found: /favicon.ico
WARNING 2025-10-16 10:56:18,545 basehttp 12660 11524 "GET /favicon.ico HTTP/1.1" 404 3037
INFO 2025-10-16 10:57:42,338 basehttp 12660 3140 "OPTIONS /api/token/ HTTP/1.1" 200 0
INFO 2025-10-16 10:57:46,595 basehttp 12660 3140 "POST /api/token/ HTTP/1.1" 200 489
INFO 2025-10-16 10:57:46,600 basehttp 12660 3140 "OPTIONS /api/users/me/ HTTP/1.1" 200 0
INFO 2025-10-16 10:57:49,688 basehttp 12660 3140 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-16 10:57:49,856 basehttp 12660 7464 "OPTIONS /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 0
INFO 2025-10-16 10:57:49,857 basehttp 12660 3140 "OPTIONS /api/dashboard/summary/ HTTP/1.1" 200 0
INFO 2025-10-16 10:57:49,877 basehttp 12660 7464 "OPTIONS /api/dashboard/summary/ HTTP/1.1" 200 0
INFO 2025-10-16 10:57:49,877 basehttp 12660 3140 "OPTIONS /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 0
INFO 2025-10-16 10:57:53,118 basehttp 12660 3140 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-16 10:57:54,605 basehttp 12660 7464 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-16 10:57:56,206 basehttp 12660 3140 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-16 10:57:59,228 basehttp 12660 7464 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-16 10:59:23,961 basehttp 12660 7464 "OPTIONS /api/stock-entries/ HTTP/1.1" 200 0
INFO 2025-10-16 10:59:23,961 basehttp 12660 3140 "OPTIONS /api/stock-entries/ HTTP/1.1" 200 0
INFO 2025-10-16 10:59:27,069 basehttp 12660 7464 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-16 10:59:30,131 basehttp 12660 7464 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-16 10:59:39,388 basehttp 12660 7464 "OPTIONS /api/customers/ HTTP/1.1" 200 0
INFO 2025-10-16 10:59:39,388 basehttp 12660 3140 "OPTIONS /api/customers/ HTTP/1.1" 200 0
INFO 2025-10-16 10:59:42,566 basehttp 12660 3140 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-16 10:59:45,634 basehttp 12660 3140 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-16 10:59:45,964 basehttp 12660 7464 "OPTIONS /api/suppliers/ HTTP/1.1" 200 0
INFO 2025-10-16 10:59:45,965 basehttp 12660 3140 "OPTIONS /api/suppliers/ HTTP/1.1" 200 0
INFO 2025-10-16 10:59:49,513 basehttp 12660 3140 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-16 10:59:53,242 basehttp 12660 3140 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-16 11:06:54,291 basehttp 12660 3660 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-16 11:06:57,547 basehttp 12660 3660 "GET /api/customers/ HTTP/1.1" 200 52
INFO 2025-10-16 11:07:59,333 basehttp 12660 3660 "POST /api/customers/ HTTP/1.1" 201 250
INFO 2025-10-16 11:08:02,736 basehttp 12660 3660 "GET /api/customers/ HTTP/1.1" 200 302
INFO 2025-10-16 11:08:51,811 basehttp 12660 3660 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-16 11:08:55,218 basehttp 12660 3660 "GET /api/suppliers/ HTTP/1.1" 200 733
INFO 2025-10-16 11:08:58,919 basehttp 12660 3660 "GET /api/customers/ HTTP/1.1" 200 302
INFO 2025-10-16 11:08:59,431 basehttp 12660 1116 "OPTIONS /api/categories/ HTTP/1.1" 200 0
INFO 2025-10-16 11:08:59,431 basehttp 12660 8548 "OPTIONS /api/products/ HTTP/1.1" 200 0
INFO 2025-10-16 11:08:59,433 basehttp 12660 9032 "OPTIONS /api/products/ HTTP/1.1" 200 0
INFO 2025-10-16 11:08:59,433 basehttp 12660 7072 "OPTIONS /api/subcategories/ HTTP/1.1" 200 0
INFO 2025-10-16 11:08:59,433 basehttp 12660 12184 "OPTIONS /api/categories/ HTTP/1.1" 200 0
INFO 2025-10-16 11:08:59,441 basehttp 12660 1116 "OPTIONS /api/subcategories/ HTTP/1.1" 200 0
INFO 2025-10-16 11:09:02,326 basehttp 12660 3660 "GET /api/customers/ HTTP/1.1" 200 302
INFO 2025-10-16 11:09:02,869 basehttp 12660 12184 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:09:02,910 basehttp 12660 7072 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:09:03,205 basehttp 12660 8548 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:09:06,262 basehttp 12660 7072 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:09:06,280 basehttp 12660 12184 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:09:06,882 basehttp 12660 8548 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:09:26,359 basehttp 12660 8548 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:09:26,359 basehttp 12660 7072 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:09:26,615 basehttp 12660 12184 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:09:37,723 basehttp 12660 12184 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-16 11:09:40,850 basehttp 12660 12184 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-16 11:09:52,882 basehttp 12660 12184 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:09:52,905 basehttp 12660 8548 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:09:53,189 basehttp 12660 7072 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:09:56,292 basehttp 12660 8548 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:09:56,292 basehttp 12660 12184 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:09:56,818 basehttp 12660 7072 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:12:11,944 basehttp 12660 12184 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-16 11:12:13,480 basehttp 12660 7072 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-16 11:12:15,093 basehttp 12660 12184 "GET /api/dashboard/recent_sales/?days=30 HTTP/1.1" 200 2
INFO 2025-10-16 11:12:18,110 basehttp 12660 7072 "GET /api/dashboard/summary/ HTTP/1.1" 200 132
INFO 2025-10-16 11:15:46,627 basehttp 12660 7072 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-16 11:15:49,745 basehttp 12660 7072 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-16 11:15:57,339 basehttp 12660 7072 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:15:57,601 basehttp 12660 5276 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:15:57,643 basehttp 12660 12184 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:16:00,791 basehttp 12660 7072 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:16:01,001 basehttp 12660 5276 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:16:01,334 basehttp 12660 12184 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:16:23,258 basehttp 12660 12184 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-16 11:16:26,340 basehttp 12660 12184 "GET /api/stock-entries/ HTTP/1.1" 200 52
INFO 2025-10-16 11:16:52,289 basehttp 12660 12184 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:16:52,289 basehttp 12660 7072 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:16:52,604 basehttp 12660 5276 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:16:55,633 basehttp 12660 7072 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:16:55,670 basehttp 12660 12184 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:16:55,870 basehttp 12660 12184 "OPTIONS /api/products/low_stock/ HTTP/1.1" 200 0
INFO 2025-10-16 11:16:56,272 basehttp 12660 5276 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:16:58,926 basehttp 12660 12184 "GET /api/products/low_stock/ HTTP/1.1" 200 347
INFO 2025-10-16 11:16:59,241 basehttp 12660 7072 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:16:59,972 basehttp 12660 5276 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:17:03,897 basehttp 12660 12184 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:17:03,921 basehttp 12660 5276 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:17:04,220 basehttp 12660 7072 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:17:08,920 basehttp 12660 7072 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-16 11:17:12,136 basehttp 12660 7072 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-16 11:17:12,415 basehttp 12660 5276 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:17:12,669 basehttp 12660 7064 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:17:12,748 basehttp 12660 12184 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:17:15,792 basehttp 12660 5276 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:17:16,030 basehttp 12660 7064 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:17:16,419 basehttp 12660 12184 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:17:47,616 basehttp 12660 5276 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:17:47,636 basehttp 12660 12184 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:17:47,959 basehttp 12660 7064 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:18:22,599 basehttp 12660 7064 "OPTIONS /api/products/2/adjust_stock/ HTTP/1.1" 200 0
ERROR 2025-10-16 11:18:25,954 log 12660 7064 Internal Server Error: /api/products/2/adjust_stock/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\Stock\Sales\views.py", line 157, in adjust_stock
    product.current_stock -= quantity
TypeError: unsupported operand type(s) for -=: 'int' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-16 11:18:25,981 basehttp 12660 7064 "POST /api/products/2/adjust_stock/ HTTP/1.1" 500 141800
INFO 2025-10-16 11:18:32,947 basehttp 12660 5276 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:18:32,948 basehttp 12660 7064 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:18:33,230 basehttp 12660 12184 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:18:39,809 basehttp 12660 12184 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-16 11:18:42,952 basehttp 12660 12184 "GET /api/users/me/ HTTP/1.1" 200 222
INFO 2025-10-16 11:18:43,256 basehttp 12660 7064 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:18:43,284 basehttp 12660 7072 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:18:43,593 basehttp 12660 5276 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:18:46,699 basehttp 12660 7072 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:18:46,700 basehttp 12660 7064 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:18:47,316 basehttp 12660 5276 "GET /api/categories/ HTTP/1.1" 200 436
ERROR 2025-10-16 11:19:11,127 log 12660 5276 Internal Server Error: /api/products/2/adjust_stock/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\Stock\Sales\views.py", line 157, in adjust_stock
    product.current_stock -= quantity
TypeError: unsupported operand type(s) for -=: 'int' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-16 11:19:11,141 basehttp 12660 5276 "POST /api/products/2/adjust_stock/ HTTP/1.1" 500 141800
ERROR 2025-10-16 11:19:16,418 log 12660 5276 Internal Server Error: /api/products/2/adjust_stock/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\Stock\Sales\views.py", line 157, in adjust_stock
    product.current_stock -= quantity
TypeError: unsupported operand type(s) for -=: 'int' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-16 11:19:16,442 basehttp 12660 5276 "POST /api/products/2/adjust_stock/ HTTP/1.1" 500 141800
ERROR 2025-10-16 11:19:21,287 log 12660 5276 Internal Server Error: /api/products/2/adjust_stock/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\Stock\Sales\views.py", line 157, in adjust_stock
    product.current_stock -= quantity
TypeError: unsupported operand type(s) for -=: 'int' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 179, in import_from_string
    return import_string(val)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\views.py", line 304, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 168, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\rest_framework\settings.py", line 182, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'stock.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'stock'.
ERROR 2025-10-16 11:19:21,331 basehttp 12660 5276 "POST /api/products/2/adjust_stock/ HTTP/1.1" 500 141800
INFO 2025-10-16 11:19:44,132 basehttp 12660 7072 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:19:44,144 basehttp 12660 5276 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:19:44,456 basehttp 12660 7064 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:26:09,353 basehttp 12660 4372 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:26:09,394 basehttp 12660 13296 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:26:09,696 basehttp 12660 6636 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:26:44,638 basehttp 12660 6636 "GET /api/products/low_stock/ HTTP/1.1" 200 347
INFO 2025-10-16 11:26:44,975 basehttp 12660 4372 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:26:45,307 basehttp 12660 13296 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:26:57,395 basehttp 12660 6636 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:26:57,409 basehttp 12660 13296 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:26:57,702 basehttp 12660 4372 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 11:27:12,497 basehttp 12660 4372 "OPTIONS /api/products/1/ HTTP/1.1" 200 0
INFO 2025-10-16 11:27:16,838 basehttp 12660 4372 "PUT /api/products/1/ HTTP/1.1" 200 345
INFO 2025-10-16 11:27:20,284 basehttp 12660 4372 "GET /api/products/ HTTP/1.1" 200 737
INFO 2025-10-16 11:27:20,292 basehttp 12660 6636 "GET /api/subcategories/ HTTP/1.1" 200 330
INFO 2025-10-16 11:27:20,566 basehttp 12660 13296 "GET /api/categories/ HTTP/1.1" 200 436
INFO 2025-10-16 12:14:01,988 autoreload 12660 10932 C:\Users\user\OneDrive\Desktop\Inventory\Stock\Sales\models.py changed, reloading.
INFO 2025-10-16 12:14:04,299 autoreload 9280 13552 Watching for file changes with StatReloader
INFO 2025-10-16 12:15:43,242 autoreload 9280 13552 C:\Users\user\OneDrive\Desktop\Inventory\Stock\Sales\serializers.py changed, reloading.
INFO 2025-10-16 12:15:44,787 autoreload 13588 12240 Watching for file changes with StatReloader
INFO 2025-10-16 12:16:56,122 autoreload 13588 12240 C:\Users\user\OneDrive\Desktop\Inventory\Stock\Sales\views.py changed, reloading.
INFO 2025-10-16 12:16:57,408 autoreload 5316 13724 Watching for file changes with StatReloader
INFO 2025-10-16 12:18:16,810 autoreload 5316 13724 C:\Users\user\OneDrive\Desktop\Inventory\Stock\Sales\urls.py changed, reloading.
INFO 2025-10-16 12:18:18,216 autoreload 13860 6776 Watching for file changes with StatReloader
INFO 2025-10-16 12:19:05,746 autoreload 13860 6776 C:\Users\user\OneDrive\Desktop\Inventory\Stock\Sales\admin.py changed, reloading.
INFO 2025-10-16 12:19:07,166 autoreload 13560 14044 Watching for file changes with StatReloader
INFO 2025-10-16 12:20:30,093 autoreload 5476 13400 Watching for file changes with StatReloader
INFO 2025-10-16 12:20:42,572 basehttp 5476 10104 "GET /admin/ HTTP/1.1" 200 16851
INFO 2025-10-16 12:20:48,928 basehttp 5476 10104 "GET /admin/Sales/sale/ HTTP/1.1" 200 15259
INFO 2025-10-16 12:20:49,282 basehttp 5476 12028 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-10-16 12:20:49,295 basehttp 5476 10104 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-10-16 12:20:49,371 basehttp 5476 10104 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-10-16 12:20:49,399 basehttp 5476 12028 "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-10-16 12:20:49,412 basehttp 5476 1576 "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-10-16 12:20:49,415 basehttp 5476 8052 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9777
INFO 2025-10-16 12:20:49,448 basehttp 5476 10104 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-10-16 12:20:49,453 basehttp 5476 1576 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-10-16 12:20:49,540 basehttp 5476 13576 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-10-16 12:20:49,636 basehttp 5476 12028 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-10-16 12:20:49,679 basehttp 5476 12028 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-10-16 12:20:52,254 basehttp 5476 9076 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-16 12:20:52,325 basehttp 5476 9076 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-10-16 12:20:52,329 basehttp 5476 12028 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
ERROR 2025-10-16 12:21:28,654 log 5476 12028 Internal Server Error: /admin/Sales/sale/add/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'outstanding_quantity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\contrib\admin\utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\contrib\admin\utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
        "%s has no field named '%s'" % (self.object_name, field_name)
    )
django.core.exceptions.FieldDoesNotExist: Sale has no field named 'outstanding_quantity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 1075, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 722, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 854, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\template\base.py", line 925, in _resolve_lookup
    current = current()
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\contrib\admin\helpers.py", line 275, in contents
    f, attr, value = lookup_field(field, obj, model_admin)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\Inventory\venv\Lib\site-packages\django\contrib\admin\utils.py", line 304, in lookup_field
    value = attr()
  File "C:\Users\user\OneDrive\Desktop\Inventory\Stock\Sales\models.py", line 288, in outstanding_quantity
    return self.quantity_ordered - self.quantity_supplied
           ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
ERROR 2025-10-16 12:21:28,809 basehttp 5476 12028 "GET /admin/Sales/sale/add/ HTTP/1.1" 500 609906
INFO 2025-10-16 12:25:23,752 autoreload 5476 13400 C:\Users\user\OneDrive\Desktop\Inventory\Stock\Sales\models.py changed, reloading.
INFO 2025-10-16 12:25:25,222 autoreload 14236 6664 Watching for file changes with StatReloader
